// Generated by tests/_helpers/scripts/generate-smoothing-fixtures.mjs; do not edit by hand.
#let cases = (
  (
    id: "smoothing-0",
    width: 120pt,
    height: 80pt,
    args: arguments(
      width: 120pt,
      height: 80pt,
      radius: 20pt,
      smoothing: 0%,
      fill: black,
    ),
    reference: arguments(
      id: "smoothing-0",
      width: 120pt,
      height: 80pt,
    ),
  ),
  (
    id: "smoothing-60",
    width: 120pt,
    height: 80pt,
    args: arguments(
      width: 120pt,
      height: 80pt,
      radius: 20pt,
      smoothing: 60%,
      fill: black,
    ),
    reference: arguments(
      id: "smoothing-60",
      width: 120pt,
      height: 80pt,
    ),
  ),
  (
    id: "smoothing-100",
    width: 120pt,
    height: 80pt,
    args: arguments(
      width: 120pt,
      height: 80pt,
      radius: 20pt,
      smoothing: 100%,
      fill: black,
    ),
    reference: arguments(
      id: "smoothing-100",
      width: 120pt,
      height: 80pt,
    ),
  ),
  (
    id: "small-radius",
    width: 80pt,
    height: 60pt,
    args: arguments(
      width: 80pt,
      height: 60pt,
      radius: 18pt,
      smoothing: 60%,
      fill: black,
    ),
    reference: arguments(
      id: "small-radius",
      width: 80pt,
      height: 60pt,
    ),
  ),
)
