// Generated by tests/_helpers/scripts/generate-smoothing-fixtures.mjs; do not edit by hand.
#let cases = (
  (
    id: "roomy-uniform",
    width: 160pt,
    height: 120pt,
    args: arguments(
      width: 160pt,
      height: 120pt,
      radius: 10pt,
      smoothing: 100%,
      fill: black,
    ),
    reference: arguments(
      id: "roomy-uniform",
      width: 160pt,
      height: 120pt,
    ),
  ),
  (
    id: "roomy-per-corner",
    width: 160pt,
    height: 120pt,
    args: arguments(
      width: 160pt,
      height: 120pt,
      radius: (
        top-left: 8pt,
        top-right: 12pt,
        bottom-right: 10pt,
        bottom-left: 6pt,
      ),
      smoothing: (
        top-left: 100%,
        top-right: 75%,
        bottom-right: 50%,
        bottom-left: 25%,
      ),
      fill: black,
    ),
    reference: arguments(
      id: "roomy-per-corner",
      width: 160pt,
      height: 120pt,
    ),
  ),
  (
    id: "zero-smoothing-pill",
    width: 150pt,
    height: 50pt,
    args: arguments(
      width: 150pt,
      height: 50pt,
      radius: 25pt,
      smoothing: 0%,
      fill: black,
    ),
    reference: arguments(
      id: "zero-smoothing-pill",
      width: 150pt,
      height: 50pt,
    ),
  ),
)
