// Generated by tests/_helpers/scripts/generate-smoothing-fixtures.mjs; do not edit by hand.
#let cases = (
  (
    id: "uniform",
    width: 84pt,
    height: 54pt,
    args: arguments(
      width: 80pt,
      height: 50pt,
      radius: 20pt,
      smoothing: 100%,
      per-edge-smoothing: true,
      stroke: 4pt + black,
    ),
    reference: arguments(
      id: "uniform",
      width: 84pt,
      height: 54pt,
    ),
  ),
  (
    id: "top-only",
    width: 86pt,
    height: 56pt,
    args: arguments(
      width: 80pt,
      height: 50pt,
      radius: 20pt,
      smoothing: 100%,
      per-edge-smoothing: true,
      stroke: (top: 6pt + black),
    ),
    reference: arguments(
      id: "top-only",
      width: 86pt,
      height: 56pt,
    ),
  ),
  (
    id: "thick-ring",
    width: 96pt,
    height: 36pt,
    args: arguments(
      width: 80pt,
      height: 20pt,
      radius: 12pt,
      smoothing: 100%,
      per-edge-smoothing: true,
      stroke: 16pt + black,
    ),
    reference: arguments(
      id: "thick-ring",
      width: 96pt,
      height: 36pt,
    ),
  ),
)
