// The SVG fixtures are checked in, generated by the pinned reference package,
// and rendered in the same fixed grid as test.typ.

#import "cases.typ": cases

#set page(width: auto, height: auto, margin: 10pt, fill: white)
#grid(
  columns: 3,
  ..cases.map(case => box(
    width: 150pt,
    height: 110pt,
    align(
      center + horizon,
      image(
        "fixtures/" + case.id + ".svg",
        width: case.width,
        height: case.height,
      ),
    ),
  )),
)
