// Generated by tests/_helpers/scripts/generate-smoothing-fixtures.mjs; do not edit by hand.
#let cases = (
  (
    id: "exponent-4",
    width: 120pt,
    height: 80pt,
    args: arguments(
      width: 120pt,
      height: 80pt,
      radius: 20pt,
      exponent: 4,
      fill: black,
    ),
    reference: arguments(
      id: "exponent-4",
      width: 120pt,
      height: 80pt,
    ),
  ),
  (
    id: "exponent-5",
    width: 120pt,
    height: 80pt,
    args: arguments(
      width: 120pt,
      height: 80pt,
      radius: 20pt,
      exponent: 5,
      fill: black,
    ),
    reference: arguments(
      id: "exponent-5",
      width: 120pt,
      height: 80pt,
    ),
  ),
  (
    id: "exponent-8",
    width: 120pt,
    height: 80pt,
    args: arguments(
      width: 120pt,
      height: 80pt,
      radius: 20pt,
      exponent: 8,
      fill: black,
    ),
    reference: arguments(
      id: "exponent-8",
      width: 120pt,
      height: 80pt,
    ),
  ),
  (
    id: "exponent-12-cap",
    width: 120pt,
    height: 80pt,
    args: arguments(
      width: 120pt,
      height: 80pt,
      radius: 20pt,
      exponent: 12,
      fill: black,
    ),
    reference: arguments(
      id: "exponent-12-cap",
      width: 120pt,
      height: 80pt,
    ),
  ),
  (
    id: "small-radius",
    width: 120pt,
    height: 80pt,
    args: arguments(
      width: 120pt,
      height: 80pt,
      radius: 10pt,
      exponent: 5,
      fill: black,
    ),
    reference: arguments(
      id: "small-radius",
      width: 120pt,
      height: 80pt,
    ),
  ),
)
